export type {
  TextbookFileType,
  TextbookStatus,
  IndexStatus,
  Textbook,
  Document,
  DocumentListParams,
  Chapter,
  KnowledgeAtomType,
  KnowledgeAtom,
  KnowledgeUnitCategory,
  KnowledgeUnit,
  ChunkMetadata,
  Chunk,
  ProcessingTask,
} from "./textbook";

export type {
  NodeType,
  RelationType,
  DependencyStrength,
  GraphNode,
  GraphEdge,
  GraphData,
  GraphFilter,
  GraphLayoutOptions,
  GraphStats,
  CoherenceViolation,
  CoherenceFix,
  CoherenceFixOption,
  KnowledgeDependency,
  AlignmentResult,
  AlignmentSignals,
  GraphEdgeRelation,
  KnowledgeGraph,
  GraphBuildRequest,
  GraphBuildResponse,
} from "./graph";

export type {
  MergeAction,
  OverlapLevel,
  MergeDecision,
  DuplicatePair,
  MergeCandidate,
  MergeRequest,
  MergeResult,
  CompressionStats,
  CompressionStrategy,
  ImportanceScore,
  DecisionVersion,
  DecisionDiff,
  DecisionDiffItem,
  AlignmentCandidate,
  DuplicateJudgment,
} from "./merge";

export type {
  Citation,
  GraphContext,
  RAGAnswer,
  RAGRequest,
  RAGQueryRequest,
  RAGIndexRequest,
  RAGIndexStatus,
  RAGResponse,
  RetrievalResult,
  RetrievalMetadata,
  HallucinationCheck,
} from "./rag";

export type {
  MessageRole,
  ChatIntent,
  ChatMessage,
  ConversationMessage,
  Conversation,
  ConversationListParams,
  SendMessageRequest,
  SendMessageResponse,
  ConversationSummary,
  IntentRecognition,
  ReferenceResolution,
  StreamingChunk,
} from "./chat";

export type {
  ApiResponse,
  ApiError,
  ApiErrorDetail,
  PaginatedResponse,
  AsyncTask,
  AsyncTaskStatus,
  AsyncTaskType,
  IntegrationReport,
  TextbookListResponse,
  TextbookDetailResponse,
  UploadResponse,
  TaskStatusResponse,
  GraphDataResponse,
  GraphStatsResponse,
  CoherenceCheckResponse,
  MergeDecisionsResponse,
  CompressionStatsResponse,
  RAGQueryResponse,
  ChatHistoryResponse,
  ConversationListResponse,
  HealthCheckResponse,
} from "./api";

export type {
  ReportOverviewStats,
  DecisionActionCounts,
  DecisionSummaryData,
  GraphSnapshot,
  GraphDelta,
  GraphComparison,
  CaseStudySource,
  CaseStudy,
  FullIntegrationReport,
  DecisionSortField,
  SortDirection,
  DecisionFilter,
  DecisionSort,
} from "./report";

export type { ProcessingStage } from "@/stores/processing";
